Add util function `to_record` to build records
burnash/gspread pull request #1377
Opened 2024-01-15 23:15 UTC by lavigne958

Add a new util function that helps building record values. Records are list of dictionaries, each dictionary has the same set of keys, they are set from the given list of headers. Each key is associated to a value from the given matrix of values. They are as many dictionaries as they are lines in the matrix.

Each line in the matrix will be associated to a dictionary, each key is associated to a value from that line in the given order.

Example:
Headers: A B C
Values:
1 2 3
7 8 9
Result: [ { A: 1, B: 2, C: 3}, {A: 7, B: 8, C: 9}]

closes #1367

2024-01-17 00:27 UTC, alifeee commented
this is good stuff, thank you :)

we should also make this function more visible to users - it should be added to the docstring of `get_all_records`

(and migration guide readme - covered by #1376)

2024-01-17 00:28 UTC, alifeee requested changes
see above comment

2024-01-17 13:06 UTC, alifeee commented
> Thanks ! It's actually shorter than what I expected 🙄

haha.. yes! a great one-liner eh

> What do you think of the outcome of that global change ?
> Are you satisfied with it ?

Do you mean the simplification of `get_all_records`? I think I am happy with it. I will have to have another look. What do you think?

2024-01-19 08:28 UTC, lavigne958 commented
> > What do you think of the outcome of that global change ?
> > Are you satisfied with it ?
> 
> Do you mean the simplification of `get_all_records`? I think I am happy with it. I will have to have another look. What do you think?

yes that's what I mean. you can once everything is merged, it might be easier to see the whole result.

I'm working currently on the docstring upgrade + migration guide (that part is quite long to explain, new functions, removed methods etc)

2024-01-19 16:05 UTC, merged

2024-01-19 16:31 UTC, alifeee commented
my apologies for merging this, I have restored the branch and reverted the merge commit with 51f9f25cd198f1ca69f530fa0a4cf6750f808097.

You may need to create a new PR :/